export const FETCHING_MESSAGE_REQUEST = 'chat/FETCHING_MESSAGE_REQUEST';
export const FETCHING_MESSAGE_FAILURE = 'chat/FETCHING_MESSAGE_FAILURE';
export const FETCHING_MESSAGE_SUCCESS = 'chat/FETCHING_MESSAGE_SUCCESS';
export const RESET_FETCHING_MESSAGE = 'chat/RESET_FETCHING_MESSAGE';

export const MERGE_MESSAGE = 'chat/MERGE_MESSAGE';
