import React from 'react';
import {StyleSheet} from 'react-native';
import PushNotification from 'react-native-push-notification';
import MainLayout from '../../layouts/MainLayout';
import {useNavigation} from '@react-navigation/native';
import {COLORS, ROUTES} from '../../constants';
import {SafeAreaView} from 'react-native-safe-area-context';
import FocusAwareStatusBar from '../../components/common/FocusAwareStatusBar';
import {Button, Text} from '@ui-kitten/components';

const NotificationScreen = () => {
  const navigation = useNavigation();
  const testPushNotif = () => {
    PushNotification.localNotification({
      /* Android Only Properties */
      channelId: 'default_notification_channel_id', // (required) channelId, if the channel doesn't exist, notification will not trigger.
      ticker: 'Xin Chao . This is ticker.', // (optional)
      showWhen: true, // (optional) default: true
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher". Use "" for no large icon.
      largeIconUrl:
        'https://riski.me/_next/image?url=%2F4yearsago.jpg&w=256&q=75', // (optional) default: undefined
      smallIcon: 'https://riski.me/_next/image?url=%2F4yearsago.jpg&w=256&q=75', // (optional) default: "ic_notification" with fallback for "ic_launcher". Use "" for default small icon.
      bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
      subText: '', // (optional) default: none
      // bigPictureUrl:
      //   'https://www.cameraegg.org/wp-content/uploads/2015/06/canon-powershot-g3-x-sample-images-1-600x400.jpg', // (optional) default: undefined
      bigLargeIcon: 'ic_launcher', // (optional) default: undefined
      bigLargeIconUrl:
        'https://riski.me/_next/image?url=%2F4yearsago.jpg&w=256&q=75', // (optional) default: undefined
      color: COLORS.primary, // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      groupSummary: false, // (optional) set this notification to be the group summary for a group of notifications, default: false
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      priority: 'high', // (optional) set notification priority, default: high
      visibility: 'public', // (optional) set notification visibility, default: private
      ignoreInForeground: false, // (optional) if true, the notification will not be visible when the app is in the foreground (useful for parity with how iOS notifications appear). should be used in combine with `com.dieam.reactnativepushnotification.notification_foreground` setting
      shortcutId: 'shortcut-id', // (optional) If this notification is duplicative of a Launcher shortcut, sets the id of the shortcut, in case the Launcher wants to hide the shortcut, default undefined
      onlyAlertOnce: false, // (optional) alert will open only once with sound and notify, default: false

      when: null, // (optional) Add a timestamp (Unix timestamp value in milliseconds) pertaining to the notification (usually the time the event occurred). For apps targeting Build.VERSION_CODES.N and above, this time is not shown anymore by default and must be opted into by using `showWhen`, default: null.
      usesChronometer: false, // (optional) Show the `when` field as a stopwatch. Instead of presenting `when` as a timestamp, the notification will show an automatically updating display of the minutes and seconds since when. Useful when showing an elapsed time (like an ongoing phone call), default: false.
      timeoutAfter: null, // (optional) Specifies a duration in milliseconds after which this notification should be canceled, if it is not already canceled, default: null

      // messageId: 'google:message_id', // (optional) added as `message_id` to intent extras so opening push notification can find data stored by @react-native-firebase/messaging module.

      actions: ['Ok', 'No'], // (Android only) See the doc for notification actions to know more
      invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true

      /* iOS only properties */
      category: '', // (optional) default: empty string

      /* iOS and Android properties */
      id: 1, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      title: 'Xin Chao Riski', // (optional)
      message: 'My Notification Message', // (required)
      userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
      playSound: true, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      // repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    });

    console.log('Test notification called');
  };

  const initialNotification = () => {
    PushNotification.popInitialNotification((notification) => {
      console.log('Initial Notification', notification);
    });
  };

  return (
    <MainLayout>
      <SafeAreaView style={styles.root}>
        <FocusAwareStatusBar barStyle="dark-content" backgroundColor="#fff" />
        <Text>NotificationScreen</Text>
        <Button onPress={initialNotification}>Initial Notification</Button>
        <Button onPress={testPushNotif}>Test Notif</Button>
      </SafeAreaView>
    </MainLayout>
  );
};


const styles = StyleSheet.create({
  root: {
    flex: 1,
    paddingHorizontal: 20,
  },
});


export default NotificationScreen;
