export const CREATE_PHRASEBOOK_REQUEST = 'phrasebook/CREATE_PHRASEBOOK_REQUEST';
export const CREATE_PHRASEBOOK_FAILURE = 'phrasebook/CREATE_PHRASEBOOK_FAILURE';
export const CREATE_PHRASEBOOK_SUCCESS = 'phrasebook/CREATE_PHRASEBOOK_SUCCESS';
export const RESET_CREATE_PRASEBOOK_STATE =
  'phrasebook/RESET_CREATE_PRASEBOOK_STATE';
