export const ROUTES = {
  ONBOARDING: 'Onboarding',
  AUTH: 'Auth',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOME: 'Home',
  DRAWER: 'Drawer',
  TAB: 'Tab',
  FORGOT_PASSWORD: 'ForgotPassword',
  SEARCH: 'Search',
  PROFILE: 'Profile',
  MEMBER: 'Member',
  MEMBER_LIST: 'MemberList',
  MEMBER_DETAILS: 'MemberDetails',
  CREATE: 'Create',
  CREATE_DISCUSSION: 'CreateDiscussion',
  DISCUSSION_LIST: 'DiscussionList',
  DISCUSSION_DETAILS: 'DiscussionDetails',
  PHRASEBOOK_LIST: 'PhraseBookList',
  CHAT: 'Chat',
  CHILLAX: 'Chillax',
  SONG: 'Song',
  FAVORITE: 'Favorite',
  SETTINGS: 'Settings',
  ABOUT: 'About',
  CONTACT: 'Contact',
  LEARN: 'Learn',
};
