export const LOGIN_WITH_SOCIAL_ACCOUNT_REQUEST =
  'auth/LOGIN_WITH_SOCIAL_ACCOUNT_REQUEST';
export const LOGIN_WITH_SOCIAL_ACCOUNT_CANCELLED =
  'auth/LOGIN_WITH_SOCIAL_ACCOUNT_CANCELLED';
export const LOGIN_WITH_SOCIAL_ACCOUNT_FAILURE =
  'auth/LOGIN_WITH_SOCIAL_ACCOUNT_FAILURE';
export const LOGIN_WITH_SOCIAL_ACCOUNT_SUCCESS =
  'auth/LOGIN_WITH_SOCIAL_ACCOUNT_SUCCESS';
export const RESET_LOGIN_WITH_SOCIAL_ACCOUNT_STATE =
  'auth/RESET_LOGIN_WITH_SOCIAL_ACCOUNT_STATE';

export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const RESET_REGISTER_STATE = 'auth/RESET_REGISTER_STATE';

export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const RESET_LOGIN_STATE = 'auth/RESET_LOGIN_STATE';

export const REVOKING_TOKEN_REQUEST = 'auth/REVOKING_TOKEN_REQUEST';
export const REVOKING_TOKEN_FAILURE = 'auth/REVOKING_TOKEN_FAILURE';
export const REVOKING_TOKEN_SUCCESS = 'auth/REVOKING_TOKEN_SUCCESS';

export const FETCHING_AUTHENTICATED_USER_REQUEST =
  'auth/FETCHING_AUTHENTICATED_USER_REQUEST';
export const FETCHING_AUTHENTICATED_USER_FAILURE =
  'auth/FETCHING_AUTHENTICATED_USER_FAILURE';
export const FETCHING_AUTHENTICATED_USER_SUCCESS =
  'auth/FETCHING_AUTHENTICATED_USER_SUCCESS';

export const SET_USER_TOKEN = 'auth/SET_USER_TOKEN';
export const RESET_USER_TOKEN = 'auth/RESET_USER_TOKEN';
export const SET_USER_DATA = 'auth/SET_USER_DATA';
export const RESET_USER_DATA = 'auth/RESET_USER_DATA';
