export const FETCHING_USER_REQUEST = 'user/FETCHING_USER_REQUEST';
export const FETCHING_USER_FAILURE = 'user/FETCHING_USER_FAILURE';
export const FETCHING_USER_SUCCESS = 'user/FETCHING_USER_SUCCESS';
export const RESET_FETCH_USER_STATE = 'user/RESET_FETCH_USER_STATE';

export const FETCHING_USER_LIST_REQUEST = 'user/FETCHING_USER_LIST_REQUEST';
export const FETCHING_USER_LIST_FAILURE = 'user/FETCHING_USER_LIST_FAILURE';
export const FETCHING_USER_LIST_SUCCESS = 'user/FETCHING_USER_LIST_SUCCESS';

/** Try with this type to reset fetching state */
export const RESET_FETCH_STATE = 'user/RESET_FETCH_STATE';
